on:
  push:
    branches:
      - master
jobs:
  publish-jar:
    runs-on: ubuntu-latest
    env:
      DB_IMAGE: my db image env value
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish to GitHub Packages
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
